language: elixir
otp_release:
  - 19.2
elixir:
  - 1.4.0
  - 1.3.4
dist: trusty
sudo: required
services:
  - postgresql
script:
  - MIX_ENV=test mix deps.compile
  - TEST_TASK=coveralls.travis ./scripts/run_tests.sh
  - MIX_ENV=test mix credo --strict
